name: Demo file read
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python for Demo
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies for demo Python project  
        run: |
          python -m pip install --upgrade pip
	  python -m pip install -r requirements.txt
      - name: Test installed package
        run: |
          python -m pip list
