name: Demo file read

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt

    - name: get latest csv file name
      run: python check_new_file.py

    - name: run main.py file with new input file
      run: python action_test.py -f ${{ env.my_csv }}

    - name: commit output
      run: |
        git config --global user.email "liuzhao9ster@gmail.com"
        git config --global user.name "odlzie"
        git add .
        git commit -m "add output"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
